CREATE TABLE users(
    id VARCHAR(255) PRIMARY KEY UNIQUE NOT NULL,
    username VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    apresentation VARCHAR(255) NOT NULL,
    address_cep VARCHAR(255) NOT NULL
);